### ISSUE TITLE
Where does NI100X writes?

### ISSUE THREAD

**Issue by joaomamede** [jdeschamps/MM-ownAdapters#1]
Hi Joran, 

This is not an issue but a request for help.

Where in NI100X.cpp does the code reads the "state" from MM and then writes to the NIDAQ?
I want to transform the State:1 comming from the Java GUI to 2**line_number.
Basically, the Java GUI variable doesn't support more than 8bits, if I use line >9 it breaks.

Thank you for any help.

**Comment by jdeschamps** [comment]
Hey, 

Sorry I totally missed your issue. I have only faint memories of the device adapter, and I only implemented the AnalogI part of the device adapter that is on this repository (a long time ago).

I believe the version on Micro-Manager is now much more advanced than it used to.

As a general rule in Micro-Manager device adapter, the changes "device adapter<->GUI" and "device adapter<->Device" are done in action handler functions, such as this one: [NI100X/NI100X.h#L144](https://github.com/micro-manager/mmCoreAndDevices/blob/717bd246cce282b7ed0f42784b19443214c7ca5a/DeviceAdapters/NI100X/NI100X.h#L144).

Look up the corresponding implementation of the function in the [.cpp file](https://github.com/micro-manager/mmCoreAndDevices/blob/717bd246cce282b7ed0f42784b19443214c7ca5a/DeviceAdapters/NI100X/NI100X.cpp#L1223).

I advise you to go to the image.sc forum for questions regarding how to understand a device adapter! (especially if it is from the official micro-manager repository).

The device adapters on this repo here are very old and just here for reference...
